// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by src/scripts/generate-i18n-keys.mjs

export const StringRes = {
  "appTitle": "appTitle",
  "homescreen": {
    "findYourTaste": "homescreen.findYourTaste",
    "scanBag": "homescreen.scanBag",
    "marketplace": "homescreen.marketplace",
    "diagnoseBrew": "homescreen.diagnoseBrew",
    "recipeAgenda": "homescreen.recipeAgenda",
    "coffeePlacesNearby": "homescreen.coffeePlacesNearby"
  },
  "scanBagScreen": {
    "title": "scanBagScreen.title",
    "subtitle": "scanBagScreen.subtitle",
    "scanLabel": "scanBagScreen.scanLabel",
    "processing": "scanBagScreen.processing",
    "resultsTitle": "scanBagScreen.resultsTitle",
    "noTextFound": "scanBagScreen.noTextFound",
    "retake": "scanBagScreen.retake",
    "captureError": "scanBagScreen.captureError",
    "permissionTitle": "scanBagScreen.permissionTitle",
    "permissionBody": "scanBagScreen.permissionBody",
    "permissionButton": "scanBagScreen.permissionButton",
    "permissionLoading": "scanBagScreen.permissionLoading",
    "backLabel": "scanBagScreen.backLabel"
  },
  "titleDefaultError": "titleDefaultError",
  "buttonDefaultError": "buttonDefaultError",
  "buttonOkIUnderstand": "buttonOkIUnderstand",
  "buttonContinue": "buttonContinue",
  "popupDetails": {
    "areYouSure": "popupDetails.areYouSure"
  },
  "steps": {
    "coffeeRoast": {
      "title": "steps.coffeeRoast.title",
      "buttonText": "steps.coffeeRoast.buttonText",
      "popupDescription": "steps.coffeeRoast.popupDescription",
      "popupButtonText": "steps.coffeeRoast.popupButtonText"
    },
    "dose": {
      "title": "steps.dose.title",
      "buttonNoScale": "steps.dose.buttonNoScale",
      "popupNoScaleMessage": "steps.dose.popupNoScaleMessage"
    },
    "extractionDuration": {
      "title": "steps.extractionDuration.title",
      "buttonIdontKnow": "steps.extractionDuration.buttonIdontKnow",
      "buttonStart": "steps.extractionDuration.buttonStart",
      "buttonStop": "steps.extractionDuration.buttonStop",
      "buttonRetake": "steps.extractionDuration.buttonRetake",
      "popupNoTimerMessage": "steps.extractionDuration.popupNoTimerMessage",
      "popupNoTimerButtonText": "steps.extractionDuration.popupNoTimerButtonText",
      "popupAutoStopMessage": "steps.extractionDuration.popupAutoStopMessage",
      "doNotShowAgain": "steps.extractionDuration.doNotShowAgain",
      "beginnerHint": "steps.extractionDuration.beginnerHint"
    },
    "yield": {
      "title": "steps.yield.title"
    },
    "tasteFeedback": {
      "title": "steps.tasteFeedback.title",
      "buttonText": "steps.tasteFeedback.buttonText",
      "happyWithResultButton": "steps.tasteFeedback.happyWithResultButton",
      "sour": "steps.tasteFeedback.sour",
      "sourDescription": "steps.tasteFeedback.sourDescription",
      "bitter": "steps.tasteFeedback.bitter",
      "bitterDescription": "steps.tasteFeedback.bitterDescription",
      "acidic": "steps.tasteFeedback.acidic",
      "acidicDescription": "steps.tasteFeedback.acidicDescription",
      "watery": "steps.tasteFeedback.watery",
      "wateryDescription": "steps.tasteFeedback.wateryDescription",
      "noCoffeeExtracted": "steps.tasteFeedback.noCoffeeExtracted",
      "noCoffeeExtractedDescription": "steps.tasteFeedback.noCoffeeExtractedDescription"
    },
    "recommendation": {
      "title": "steps.recommendation.title",
      "applyAdvice": "steps.recommendation.applyAdvice"
    }
  },
  "recipeAgenda": {
    "title": "recipeAgenda.title"
  },
  "diagnoseSuccess": {
    "title": "diagnoseSuccess.title",
    "subtitle": "diagnoseSuccess.subtitle",
    "description": "diagnoseSuccess.description",
    "primaryCta": "diagnoseSuccess.primaryCta",
    "secondaryCta": "diagnoseSuccess.secondaryCta"
  }
} as const;

// Deep type helper to extract all string values from nested objects
type LeafValues<T> = T extends string
  ? T
  : T extends Record<string, any>
  ? LeafValues<T[keyof T]>
  : never;

export type TranslationKey = LeafValues<typeof StringRes>;
