// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by src/scripts/generate-i18n-keys.mjs

export const StringRes = {
  "appTitle": "appTitle",
  "buttons": {
    "findYourTaste": "buttons.findYourTaste",
    "marketplace": "buttons.marketplace",
    "diagnoseBrew": "buttons.diagnoseBrew",
    "recipeAgenda": "buttons.recipeAgenda",
    "coffeePlacesNearby": "buttons.coffeePlacesNearby",
    "continue": "buttons.continue"
  },
  "defaultErrorTitle": "defaultErrorTitle",
  "defaultErrorButtonText": "defaultErrorButtonText",
  "steps": {
    "coffeeType": {
      "title": "steps.coffeeType.title"
    },
    "dose": {
      "title": "steps.dose.title",
      "buttonNoScale": "steps.dose.buttonNoScale",
      "popupNoScaleMessage": "steps.dose.popupNoScaleMessage",
      "popupNoScaleButtonText": "steps.dose.popupNoScaleButtonText"
    },
    "extractionDuration": {
      "title": "steps.extractionDuration.title",
      "buttonIdontKnow": "steps.extractionDuration.buttonIdontKnow",
      "popupNoTimerMessage": "steps.extractionDuration.popupNoTimerMessage",
      "popupNoTimerButtonText": "steps.extractionDuration.popupNoTimerButtonText"
    },
    "tasteFeedback": {
      "title": "steps.tasteFeedback.title",
      "buttonText": "steps.tasteFeedback.buttonText",
      "sour": "steps.tasteFeedback.sour",
      "sourDescription": "steps.tasteFeedback.sourDescription",
      "bitter": "steps.tasteFeedback.bitter",
      "bitterDescription": "steps.tasteFeedback.bitterDescription",
      "acidic": "steps.tasteFeedback.acidic",
      "acidicDescription": "steps.tasteFeedback.acidicDescription",
      "watery": "steps.tasteFeedback.watery",
      "wateryDescription": "steps.tasteFeedback.wateryDescription"
    },
    "recommendation": {
      "title": "steps.recommendation.title"
    }
  }
} as const;

// Deep type helper to extract all string values from nested objects
type LeafValues<T> = T extends string
  ? T
  : T extends Record<string, any>
  ? LeafValues<T[keyof T]>
  : never;

export type TranslationKey = LeafValues<typeof StringRes>;
